{% set name = "envkernel" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envkernel-{{ version }}.tar.gz
  sha256: dcdc64e64758fa9a73187c7413a74f8a85cdfaf0c68a9c2e05f75d0db859fd13

build:
  number: 0
  noarch: python
  entry_points:
    - envkernel=envkernel:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jupyter_client
    - python >=3.6

test:
  imports:
    - envkernel
  commands:
    - pip check
    - envkernel --help
  requires:
    - pip

about:
  home: https://github.com/NordicHPC/envkernel
  summary: Jupyter kernels manipulation and in other environments.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
