{% set name = "envkernel" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/envkernel-{{ version }}.tar.gz
  sha256: 0d3a547f155b4e5c43339d96bb0c574f6d29d7c31179f661bacb7107d4c27a4b

build:
  number: 0
  noarch: python
  entry_points:
    - envkernel=envkernel:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jupyter_client
    - python >={{ python_min }}

test:
  imports:
    - envkernel
  commands:
    - pip check
    - envkernel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NordicHPC/envkernel
  summary: Jupyter kernels manipulation and in other environments.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
